name: podiz
description: A new Flutter project.

#* before release build
# https://pub.dev/packages/flutter_local_notifications#release-build-configuration

#* iOS setup
# https://pub.dev/packages/flutter_local_notifications#-ios-setup



# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.4"

dependencies:
  app_settings: ^4.1.8
  cloud_firestore: ^3.4.2
  cloud_functions: ^3.3.3
  collection: ^1.16.0
  connectivity: ^3.0.6
  custom_refresh_indicator: ^1.2.1
  device_info_plus: ^4.1.2
  equatable: ^2.0.3
  firebase_auth: ^3.6.1
  firebase_core: 1.20.0
  firebase_database: ^9.1.1
  firebase_dynamic_links: ^4.3.9
  firebase_messaging: ^12.0.1
  firebase_storage: ^10.2.11
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.0.4
  flutter_keyboard_visibility: ^5.3.0
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^9.9.1
  flutter_locales: ^2.0.1
  flutter_riverpod: ^2.0.0-dev.9
  flutter_svg: ^1.1.1+1
  flutter_svg_provider: ^1.0.3
  flutter_web_auth_2: 1.0.0
  flutterfire_ui: ^0.4.3+4
  go_router: ^4.2.7
  google_fonts: ^3.0.1
  http: ^0.13.5
  json_annotation: ^4.4.0
  lottie: ^1.4.2
  mixpanel_flutter: ^1.6.0
  rxdart: ^0.27.4
  share_plus: ^4.0.10+1
  skeletons: ^0.0.3
  spotify_sdk: ^2.3.0
  streaming_shared_preferences: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1

flutter_icons:
  android: true
  image_path: "assets/app_icon/ios_app_icon.png"
  adaptive_icon_foreground: "assets/app_icon/ic_launcher_foreground.png"
  adaptive_icon_background: "#2B0047"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/app_icon/ios_app_icon.png"
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/app_icon/notification_tray.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app_icon/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
    - assets/locales/
    - assets/lottie/
